version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: socialapp_db
      POSTGRES_USER: socialapp_user
      POSTGRES_PASSWORD: socialapp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/SocialApp
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=socialapp_db
      - DB_USER=socialapp_user
      - DB_PASSWORD=socialapp_password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: